name: Autograding Tests
'on':
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: "spin returns a random value in 1..sectors (40)"
        id: spin
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "spin returns a random value in 1..sectors"
          setup-command: ''
          command: sh .github/grade.sh SpinTest
          timeout: 5
          max-score: 40
      - name: "currentRun tracks the length of the current run (60)"
        id: currentrun
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "currentRun tracks the length of the current run"
          setup-command: ''
          command: sh .github/grade.sh CurrentRunTest
          timeout: 5
          max-score: 60
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          SPIN_RESULTS: "${{ steps.spin.outputs.result }}"
          CURRENTRUN_RESULTS: "${{ steps.currentrun.outputs.result }}"
        with:
          runners: spin,currentrun
